In [1]:
import numpy as np
a0 = np.zeros((3, 3))
a0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
a1 = np.ones((3, 2))
a1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
a2 = np.arange(10, 160, 10).reshape(3, 5)
a2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [6]:
a3 = np.vstack([np.hstack([a0, a1]), a2])
a3

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [7]:
np.vstack([a3, a3])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [8]:
x = np.arange(3)
y = np.arange(5)

In [9]:
X, Y = np.meshgrid(x, y)

In [10]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [11]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [13]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [14]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [15]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 7 ms


In [16]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [17]:
%%time
z = x + y

Wall time: 0 ns


In [18]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [21]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [22]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [23]:
y = np.arange(5).reshape(5,1)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [24]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [30]:
r = np.random.rand(5, 6) * 10
r

array([[5.82437809, 2.0398315 , 7.0575818 , 6.10733395, 5.63713511,
        5.57037324],
       [4.98159128, 4.57761718, 6.25335582, 7.46555728, 7.66788782,
        2.61540125],
       [8.79301979, 1.55493469, 1.74829467, 5.22220722, 9.01290435,
        9.13501305],
       [2.19676723, 7.82752497, 6.39054349, 7.95466825, 8.66311376,
        3.03782999],
       [0.65901692, 6.93786487, 6.56355473, 9.84453128, 4.83249119,
        5.37337613]])

In [31]:
r.max()

9.844531284692208

In [32]:
r.sum(axis=1)

array([32.23663369, 33.56141063, 35.46637377, 36.07044768, 34.21083512])

In [33]:
r.max(axis=1)

array([7.0575818 , 7.66788782, 9.13501305, 8.66311376, 9.84453128])

In [36]:
r.mean(axis=0)

array([4.49095466, 4.58755464, 5.6026661 , 7.3188596 , 7.16270645,
       5.14639873])

In [37]:
r.min(axis=0)

array([0.65901692, 1.55493469, 1.74829467, 5.22220722, 4.83249119,
       2.61540125])

In [42]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [43]:
np.mean(x)

4.8076923076923075