In [1]:
import numpy as np
a0 = np.zeros((3, 3))
a0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [2]:
a1 = np.ones((3, 2))
a1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [3]:
a2 = np.arange(10, 160, 10).reshape(3, 5)
a2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [4]:
a3 = np.vstack([np.hstack([a0, a1]), a2])
a3

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [5]:
np.vstack([a3, a3])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [6]:
x = np.arange(3)
y = np.arange(5)

In [7]:
X, Y = np.meshgrid(x, y)

In [8]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [9]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [10]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [11]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [12]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

Wall time: 6.99 ms


In [13]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [14]:
%%time
z = x + y

Wall time: 0 ns


In [15]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [16]:
x = np.vstack([range(7)[i:i + 3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [17]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [18]:
y = np.arange(5).reshape(5,1)
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [19]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [20]:
r = np.random.rand(5, 6) * 10
r

array([[3.85321051, 1.92397292, 2.25585135, 3.73638361, 1.02301915,
        0.82363998],
       [2.79519649, 2.75423217, 3.2294334 , 0.58095086, 6.29525557,
        6.72623576],
       [6.57021077, 8.98364925, 7.99522339, 6.93972291, 5.46642066,
        5.27431441],
       [4.45526263, 6.35307988, 0.71390941, 3.68425769, 7.95682375,
        8.91280586],
       [2.98921637, 3.96050914, 7.78352526, 7.89317366, 7.52432797,
        2.69974177]])

In [21]:
r.max()

8.983649245155231

In [22]:
r.sum(axis=1)

array([13.61607754, 22.38130425, 41.22954138, 32.07613921, 32.85049416])

In [23]:
r.max(axis=1)

array([3.85321051, 6.72623576, 8.98364925, 8.91280586, 7.89317366])

In [24]:
r.mean(axis=0)

array([4.13261935, 4.79508867, 4.39558856, 4.56689775, 5.65316942,
       4.88734755])

In [25]:
r.min(axis=0)

array([2.79519649, 1.92397292, 0.71390941, 0.58095086, 1.02301915,
       0.82363998])

In [26]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [27]:
np.mean(x)

4.8076923076923075

In [28]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [29]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [30]:
index, count

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))

In [31]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)

In [32]:
import pandas as pd 
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [33]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [34]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [35]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [36]:
df["2010-2015 증가율"] *= 100
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [37]:
df["2005-2010 증가율"] = ((df["2010"] - df["2005"]) / df["2005"] * 100).round(2)
df

지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972           2.83          -1.34
부산  경상권  3448737  3393191  3512547  3655437           1.63          -3.40
인천  수도권  2890451  2632035  2517680  2466338           9.82           4.54
대구  경상권  2466052  2431774  2456016  2473990           1.41          -0.99

In [42]:
data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [39]:
s = df['수학']
s

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [44]:
sub_df = pd.DataFrame((df[['국어']], df[['영어']]), columns=['국어','영어'])
sub_df

ValueError: Shape of passed values is (2, 1), indices imply (2, 2)